applications-accept-decline:
    path: /accept-decline/{id}/{answer}/{studentId}
    defaults: { _controller: AppBundle:Applications:acceptDecline, id: 0, studentId: 0, answer: 0 }
    requirements:
        id: \d+
        answer: 0|1
        studentId: \d+

applications-pdf-ajax:
    path: /pdf-ajax
    defaults: { _controller: AppBundle:Applications:generatePdfAjax }
    options:
        expose: true

applications-pdf-index:
    path: /view
    defaults: { _controller: AppBundle:Applications:index}

application-pdf-download:
    path: /download-form/{filename}
    defaults: { : AppBundle:Applications:downloadApplicationForm, filename: '' }