filter-projects:
    path: /list
    defaults: { _controller: AppBundle:ProjectFilter:index }

filter-projects-ajax:
    path: /list-ajax
    defaults: { _controller: AppBundle:ProjectFilter:listAjax }
    options:
        expose: true

project-view:
    path: /view/{id}
    defaults: { _controller: AppBundle:ProjectFilter:viewProject, id: 0 }
    requirements:
        id: \d+

project-apply:
    path: /apply/{id}
    defaults: { _controller: AppBundle:ProjectFilter:applyProject, id: 0 }
    requirements:
        id: \d+
    options:
        expose: true

project-add:
    path: /add-project
    defaults: { _controller: AppBundle:ProjectFilter:addProject }

project-list-by-professor:
    path: /show-all
    defaults: { _controller: AppBundle:ProjectFilter:listProjectsByProfessor }

project-edit:
    path: /edit/{id}
    defaults: { _controller: AppBundle:ProjectFilter:projectEdit, id: 0 }
    requirements:
        id: \d+

project-delete:
    path: /delete/{id}
    defaults: { _controller: AppBundle:ProjectFilter:projectDelete, id: 0 }
    requirements:
        id: \d+
    options:
        expose: true

project-recent:
    path: /recent
    defaults: { _controller: AppBundle:ProjectFilter:recentProjectsAjax }
    options:
        expose: true