user:
    resource: "@UserBundle/Resources/config/routing/user-routing.yml"
    prefix: /profile

register_user:
    path: /register_user
    defaults: { _controller: UserBundle:User:register }

confirm_user:
    path: /confirm_user
    defaults: { _controller: UserBundle:User:confirmDeclineUser, answer: 0, userId: 0 }
    requirements:
        answer: 0|1
        userId: \d+