security:
    resource: "@AppBundle/Resources/config/routing/security-routing.yml"

default:
    resource: "@AppBundle/Resources/config/routing/default-routing.yml"
    prefix:   /

project:
    resource: "@AppBundle/Resources/config/routing/project-routing.yml"
    prefix: /projects

admin:
    resource: "@AppBundle/Resources/config/routing/admin-routing.yml"
    prefix: /admin

applications:
    resource: "@AppBundle/Resources/config/routing/applications-routing.yml"
    prefix: /applications
